version: '3'

services:
  discovery:
    image: todo-discovery:master
    expose:
      - 8761
    ports:
      - 8761:8761
    environment:
      PROFILE: docker
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    image: todo-gateway:master
    ports:
      - 8081:8081
    depends_on:
      - discovery
    environment:
      PROFILE: docker
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  todo:
    image: todo:master
    links:
      - todo-mongodb
    deploy:
      replicas: 2
    environment:
      PROFILE: docker
    depends_on:
      - discovery
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  todo-mongodb:
    image: mongo
    expose:
        - 27017
    ports:
      - 27017:27017


