eureka:
  client:
    enabled: false
    fetchRegistry: true
    registerWithEureka: false

---
server:
  port: 0

spring:
  profiles: docker
  data:
    mongodb:
      uri: mongodb://todo-mongodb:27017/todo
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true